### ISSUE TITLE
hyphens are legit in class names

### ISSUE THREAD

**Issue by docwhat** [laurilehmijoki/tomcat7_rhel#4]
If you look at [tomcat-application.pp](https://github.com/laurilehmijoki/tomcat7_rhel/blob/master/manifests/tomcat-application.pp) you'll see that the hyphens in `tomcat7_rhel::tomcat-application` and `tomcat7_rhel::tomcat-manager` are highlighted in red.

My understanding of puppet is that hyphens in class names are not allowed.

**Comment by AlexCline** [comment]
According to the [Puppet Language Guide](http://docs.puppetlabs.com/guides/language_guide.html):

> Class names, module names, and the names of defined and custom resource types should be restricted to 
> lowercase alphanumeric characters and underscores, and should begin with a lowercase letter; that is, they should 
> match the expression [a-z][a-z0-9_]*.

**Comment by laurilehmijoki** [comment]
Thanks for pointing out the incorrect namings. Let's see how soon I have time to fix them and release a new backwards incompatible version.

**Comment by laurilehmijoki** [comment]
I converted the hypens into underscores. These changes are released in version 1.0.0, which **breaks backward compatibility**. See https://github.com/laurilehmijoki/tomcat7_rhel/blob/master/changelog.md#100 for how to migrate.
